name: Auto Daily Post

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC daily
  workflow_dispatch:

permissions:  # Add this permissions block
  contents: write  # This enables push access

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for git operations

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pyyaml python-frontmatter

      - name: Run post generator
        run: python .scripts/daily_post.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@users.noreply.github.com"
          git add _posts/
          git commit -m "Auto: New daily post [skip ci]" || echo "No changes to commit"
          git push
